{%- macro lkp_normalization(SOURCE_SYSTEM,LOOKUP_CATEGORY,REFERENCE_FIELD,SOURCE_VALUE,ALIAS) -%}
(   SELECT SOURCE_SYSTEM, LOOKUP_CATEGORY, REFERENCE_FIELD, SOURCE_VALUE, NORMALIZED_VALUE, ROW_NUMBER() OVER (PARTITION BY SOURCE_SYSTEM, LOOKUP_CATEGORY, REFERENCE_FIELD, SOURCE_VALUE ORDER BY SOURCE_VALUE) RW_NUM FROM ( {{ ref('src_ref_normalization_xref')}} ) ) {{ALIAS}}
    ON {{ALIAS}}.SOURCE_SYSTEM = {{ SOURCE_SYSTEM }}
    AND {{ALIAS}}.LOOKUP_CATEGORY = '{{ LOOKUP_CATEGORY }}'
    AND {{ALIAS}}.REFERENCE_FIELD = '{{ REFERENCE_FIELD }}'
    AND {{ALIAS}}.SOURCE_VALUE= {{SOURCE_VALUE }}
    AND {{ALIAS}}.RW_NUM = 1
{% endmacro %}
