{%- macro lkp_exchange_rate_month(FROM_CURRENCY_CODE ,TO_CURRENCY_CODE,FISCAL_YEAR_PERIOD_NO,EXCH_RATE_TYPE,ALIAS) -%}
(SELECT FROM_CURRENCY_CODE ,TO_CURRENCY_CODE,FISCAL_YEAR_PERIOD_NO,EXCH_RATE_TYPE,CURR_CONVERSION_RT,
ROW_NUMBER() over (partition by FROM_CURRENCY_CODE ,TO_CURRENCY_CODE,FISCAL_YEAR_PERIOD_NO,EXCH_RATE_TYPE order by FROM_CURRENCY_CODE ,TO_CURRENCY_CODE,FISCAL_YEAR_PERIOD_NO,EXCH_RATE_TYPE ) AS ROW_NUM
    FROM ( {{ ref('src_currency_exch_rate_mth_dim')}} ) ) {{ALIAS}}
    ON {{ALIAS}}.FROM_CURRENCY_CODE = {{ FROM_CURRENCY_CODE }}
    AND {{ALIAS}}.TO_CURRENCY_CODE = {{ TO_CURRENCY_CODE }}
    AND {{ALIAS}}.FISCAL_YEAR_PERIOD_NO = {{ FISCAL_YEAR_PERIOD_NO }}
    AND {{ALIAS}}.EXCH_RATE_TYPE = {{ EXCH_RATE_TYPE }}
    AND {{ALIAS}}.ROW_NUM =1
{% endmacro %}